name: Unit Tests

on:
  push:
    branches:
    - master
    - development

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Performing Unit Tests
      run: |
        cd tests/
        python3 -c 'import os; import sys; sys.path.append(os.path.abspath("../src/")); from arctasks.resolve import InitCheckout; InitCheckout().dir_check()'
        python3 -m unittest -v ./test_*.py
